spring:
  cloud:
    gateway:
      routes:
#        - id: ee_backend_users-service_*
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: formality-service
          uri: lb://formality-service
          predicates:
            - Path=/api/formality/**
          filters:
            - StripPrefix=2
